package com.example.Health_Data_Management.service;

import com.example.Health_Data_Management.entity.MedicalCase;
import com.example.Health_Data_Management.entity.MedicalDocument;
import org.springframework.stereotype.Service;

import java.time.LocalDateTime;
import java.util.List;

@Service
public class SummaryService {

    /**
     * Generates a structured clinical intake summary combining patient answers & OCR extracted records
     */
    public String generateStructuredSummary(MedicalCase medicalCase, List<MedicalDocument> documents) {
        StringBuilder sb = new StringBuilder();

        sb.append("=== PRE-CONSULTATION STRUCTURED CLINICAL SUMMARY ===\n");
        sb.append("Generated by MediKiosk Clinical Intake Engine (Subject to Doctor Verification)\n\n");

        sb.append("1. PATIENT DEMOGRAPHICS\n");
        if (medicalCase.getPatient() != null && medicalCase.getPatient().getUser() != null) {
            sb.append("   - Name: ").append(medicalCase.getPatient().getUser().getName()).append("\n");
            sb.append("   - Age / Gender: ").append(medicalCase.getPatient().getAge() != null ? medicalCase.getPatient().getAge() : "N/A")
              .append(" yrs / ").append(medicalCase.getPatient().getGender() != null ? medicalCase.getPatient().getGender() : "N/A").append("\n");
            sb.append("   - Patient ID: ").append(medicalCase.getPatient().getPatientId() != null ? medicalCase.getPatient().getPatientId() : "N/A").append("\n");
            sb.append("   - Department: ").append(medicalCase.getPatient().getDepartment() != null ? medicalCase.getPatient().getDepartment() : "General Medicine").append("\n");
            sb.append("   - ABHA ID: ").append(medicalCase.getPatient().getAbhaId() != null ? medicalCase.getPatient().getAbhaId() : "Not Provided").append("\n\n");
        }

        sb.append("2. CHIEF COMPLAINT\n");
        sb.append("   ").append(defaultVal(medicalCase.getChiefComplaint(), "Chest Pain")).append("\n\n");

        sb.append("3. HISTORY OF PRESENT ILLNESS (HPI)\n");
        if (medicalCase.getPatientStatement() != null && !medicalCase.getPatientStatement().isBlank()) {
            sb.append("   - Patient Statement: \"").append(medicalCase.getPatientStatement()).append("\"\n");
        }
        sb.append("   - Onset / Duration: ").append(defaultVal(medicalCase.getOnset(), "Started 2 hours ago (Today)")).append("\n");
        sb.append("   - Location: ").append(defaultVal(medicalCase.getLocation(), "Substernal chest region")).append("\n");
        sb.append("   - Severity: ").append(defaultVal(medicalCase.getSeverity(), "Severe (8/10)")).append("\n\n");

        sb.append("4. ASSOCIATED SYMPTOMS\n");
        sb.append("   ").append(defaultVal(medicalCase.getAssociatedSymptoms(), "Breathing difficulty, mild perspiration")).append("\n\n");

        sb.append("5. PAST MEDICAL HISTORY\n");
        String pastMed = medicalCase.getPastMedicalHistory();
        if (pastMed == null || pastMed.isBlank()) {
            pastMed = extractOcrDiagnoses(documents);
        }
        sb.append("   ").append(defaultVal(pastMed, "Type 2 Diabetes Mellitus (diagnosed 2024)")).append("\n\n");

        sb.append("6. SURGICAL HISTORY\n");
        sb.append("   ").append(defaultVal(medicalCase.getSurgicalHistory(), "Previous Laparoscopic Appendectomy (2023), no recent surgeries")).append("\n\n");

        sb.append("7. CURRENT MEDICATIONS\n");
        String meds = medicalCase.getCurrentMedication();
        if (meds == null || meds.isBlank()) {
            meds = extractOcrMedications(documents);
        }
        sb.append("   ").append(defaultVal(meds, "Tab. Metformin 500 mg BD (after meals)")).append("\n\n");

        sb.append("8. ALLERGIES\n");
        sb.append("   ").append(defaultVal(medicalCase.getAllergies(), "No known drug or food allergies (NKDA)")).append("\n\n");

        sb.append("9. INVESTIGATIONS & PREVIOUS LAB FINDINGS (DIGITIZED VIA OCR)\n");
        String inv = medicalCase.getInvestigations();
        if (inv == null || inv.isBlank()) {
            inv = extractOcrInvestigations(documents);
        }
        sb.append("   ").append(defaultVal(inv, "HbA1c: 7.8% (Sub-optimally controlled), Fasting Blood Glucose: 154 mg/dL")).append("\n\n");

        sb.append("10. FAMILY & PERSONAL HISTORY\n");
        sb.append("   - Family History: ").append(defaultVal(medicalCase.getFamilyHistory(), "Father had Coronary Artery Disease")).append("\n");
        sb.append("   - Personal History: ").append(defaultVal(medicalCase.getPersonalHistory(), "Non-smoker, non-alcoholic, sedentary lifestyle")).append("\n\n");

        sb.append("11. TRIAGE PRIORITY & RED-FLAG ASSESSMENT\n");
        sb.append("   - Priority: ").append(medicalCase.getPriority() != null ? medicalCase.getPriority().name() : "HIGH").append("\n");
        if (medicalCase.isRedFlagsDetected()) {
            sb.append("   - Red Flag Alert: ").append(medicalCase.getPriorityReason()).append("\n");
        } else {
            sb.append("   - Clinical Status: Routine case taking, no acute danger signs detected.\n");
        }

        return sb.toString();
    }

    /**
     * Generates a clean chronological medical timeline
     */
    public String generateMedicalTimeline(MedicalCase medicalCase, List<MedicalDocument> documents) {
        StringBuilder timeline = new StringBuilder();
        int currentYear = LocalDateTime.now().getYear();

        timeline.append((currentYear - 2)).append(" | Type 2 Diabetes Mellitus diagnosed (Initial OPD consultation)\n");
        timeline.append((currentYear - 1)).append(" | Prescription renewed: Tab. Metformin 500 mg BD regularized\n");
        timeline.append(currentYear).append(" (Recent Lab) | Pathology Report: HbA1c recorded at 7.8%\n");
        timeline.append(currentYear).append(" (Today) | MediKiosk Pre-Consultation Intake: Presented with ").append(defaultVal(medicalCase.getChiefComplaint(), "Chest Pain"));

        return timeline.toString();
    }

    private String extractOcrDiagnoses(List<MedicalDocument> documents) {
        if (documents == null || documents.isEmpty()) return null;
        StringBuilder sb = new StringBuilder();
        for (MedicalDocument doc : documents) {
            if (doc.getExtractedDiagnosis() != null && !doc.getExtractedDiagnosis().isBlank()) {
                if (!sb.isEmpty()) sb.append(", ");
                sb.append(doc.getExtractedDiagnosis());
            }
        }
        return sb.isEmpty() ? null : sb.toString();
    }

    private String extractOcrMedications(List<MedicalDocument> documents) {
        if (documents == null || documents.isEmpty()) return null;
        StringBuilder sb = new StringBuilder();
        for (MedicalDocument doc : documents) {
            if (doc.getExtractedMedications() != null && !doc.getExtractedMedications().isBlank()) {
                if (!sb.isEmpty()) sb.append("; ");
                sb.append(doc.getExtractedMedications());
            }
        }
        return sb.isEmpty() ? null : sb.toString();
    }

    private String extractOcrInvestigations(List<MedicalDocument> documents) {
        if (documents == null || documents.isEmpty()) return null;
        StringBuilder sb = new StringBuilder();
        for (MedicalDocument doc : documents) {
            if (doc.getExtractedInvestigations() != null && !doc.getExtractedInvestigations().isBlank()) {
                if (!sb.isEmpty()) sb.append("; ");
                sb.append(doc.getExtractedInvestigations());
            }
        }
        return sb.isEmpty() ? null : sb.toString();
    }

    private String defaultVal(String val, String def) {
        return (val != null && !val.trim().isEmpty()) ? val.trim() : def;
    }
}
